### ISSUE TITLE
Disabling MapStats and PlayerStats block is ignored on load up

### ISSUE THREAD

**Issue by NumbaOneIsTW** [zAlweNy26/AlweStats#30]
I've disabled the MapStats and PlayerStats blocks within the config and I used my normal save as well as my mod testing save (this one had almost no other mods installed) and both blocks features were still activated on loadup. 
The following screenshot if from my normal save but it is still applicable to the testing save.
![mapstats_disabled](https://user-images.githubusercontent.com/84079395/167325621-0af38aeb-d420-4d38-9590-97f06f4e439e.png)

Relogging didn't fix this issue either. Deleting the config and reconfiguring a new one also didn't fix the issue.

**Comment by zAlweNy26** [comment]
Thanks for the warning, I will check about that as soon as I can.

**Comment by zAlweNy26** [comment]
This happens because the "enableMapStats" and "enablePlayerStats" only enable/disable their equivalent block. The config setting doesn't work with everything related to it. You can read from the config setting description, "Toggle the PlayerStats block" or "Toggle the MapStats block". That's different for EntityStats and EnvStats, which don't have blocks, in fact their config setting description is "Toggle the EntityStats section" and "Toggle the EnvStats section". Please tell me if it is clear now.

**Comment by LeChatTuxedo** [comment]
Ah, confusing but I think I understand. Unfortunate you can't turn off the sections, the pinning breaks any other mod that adds custom pins even if you disable them.

**Comment by zAlweNy26** [comment]
> Ah, confusing but I think I understand. Unfortunate you can't turn off the sections, the pinning breaks any other mod that adds custom pins even if you disable them.

Are you sure? Which mods are having problems with mine? So I will try to fix this.
Anyway if you have a better way to explain the config setting, I will hear you!

**Comment by LeChatTuxedo** [comment]
I've had issues with AlweStats playing poorly with the following mods:
[https://valheim.thunderstore.io/package/Tekla/QoLPins/](url)
[https://valheim.thunderstore.io/package/Smoothbrain/TargetPortal/](url)

The reason I was hoping there was a way to disable the MapStats config section was because even with all features within the section disabled, it still plays poorly with the above mods.

Perhaps a better way to explain the settings would be differentiating between the "block" and "section". I take it "block" pertains to the block that is displayed on screen while in game and "section" is the block of config options within the configuration.
