### ISSUE TITLE
Font size resets to default

### ISSUE THREAD

**Issue by 4Magma** [zAlweNy26/AlweStats#44]
**Describe the bug**
- Font size is always default.

**To Reproduce**
- i set font size to 24 (or 36 for clocs) because of bad eyes (Config Manager)
- after relogin sizes were restored to default
- set them again and close game
- check cfg file for my values (ok)
- start game, but default values are back
- other changes like str format for coordinates are ok

**Expected behavior**

**Screenshots**

**Comment by zAlweNy26** [comment]
Have you tried to delete the configuration file and let the game recreate it? It could also be a licensing issue with the operating system. I don’t know what to change because it always worked and I never touched it again and since it appeared now, I think it’s your problem. Let me know if you can fix it.

**Comment by 4Magma** [comment]
there are 2 cfg ...
AlweStats.cfg and Alwe.AlweStats.cfg
after deleting (... renaming to keep my values) 
Alwe.AlweStats.cfg
was created.

**Comment by zAlweNy26** [comment]
Yes, I had to change the configuration file name, the new one is Alwe.AlweStats.cfg
