### ISSUE TITLE
NullReference in EntityStats UpdateHuds

### ISSUE THREAD

**Issue by NakulDK** [zAlweNy26/AlweStats#54]
**Describe the bug**
![image](https://user-images.githubusercontent.com/45997053/216778472-112ba38b-a00e-4ebf-8856-c6f1d7e83e92.png)
1. I see this error whenever I'm near a player and the HP bar pops up.
2. Was in a private world with 7-8 player and saw some strange behavior from the HP bar.
![image](https://user-images.githubusercontent.com/45997053/216778785-6397a780-fe09-4c40-935e-e50f5ac60ed7.png)
![image](https://user-images.githubusercontent.com/45997053/216778789-352c9048-0f71-4e16-9070-8016492cfca6.png)

**To Reproduce**
1. Play near another player :)
2. Perhaps a combo of manyplayers and average computer hosting? Can't recreate.

**Expected behavior**
2. No line and actual HP number and %

**Comment by zAlweNy26** [comment]
Thanks for reporting this, it's difficult for me to make these online things work because I have nobody to play with.
I'll check if there are some checks I'm missing.
Are you playing with other mods that manage health bars or that show texts above players?
Does the problem persist even if you have only mobs around?

**Comment by NakulDK** [comment]
No issues when solo or far enough away from other players :)
add me on steam, I'll help out :)
I don't think I have any other mods doing any interface stuff besides the "equipment and quickslots" from randyknapp

**Comment by zAlweNy26** [comment]
I should have fixed it. Wait until I upload the next patch :)
